Parking/parking/routes/web.php
<?php

Route::get('/', function () {
    return view('main_page');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {

    Route::get('show_auto', 'ClientsController@on_parking_now')->name('show_auto');
    Route::get('status_off/{id}', 'ClientsController@status_off');
    Route::post('status_on', 'ClientsController@status_on')->name('status_on');
    Route::get('get_auto', 'ClientsController@get_auto')->name('get_auto');
    Route::resource('clients', 'ClientsController', ['names' => [
        'create' => 'create_record',
        'edit' => 'edit_record',
        'destroy' => 'delete_record',
        'store' => 'client_store'
    ]]);

});

Parking/parking/resources/views/add_client.blade.php
@extends('layouts.main_template')
@section('content')
<div class="container">
  <div class="row">
    <h1>Добавление нового клиента</h1>
    <br>
    <form action="{{ route('client_store') }}" method="post">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <div class="col-md-8">
        <p class="lead"> Информация о клиенте </p>
      </div>
      <div class="form-group col-md-8 {{$errors->has('full_name') ? 'has-error' : ''}}">
        <label for="full_name" >ФИО</label>
        <input class="form-control" name="full_name" id="full_name" type="text" minlength="3" lvalue="{{old('full_name')}}" @if($errors->has('full_name')) autofocus @endif autofocus>
        @if($errors->has('full_name'))
          <span class="help-block">
            <strong> {{$errors->first('full_name')}} </strong>
          </span>
        @endif
      </div>
      <div class="form-group col-md-8">
        <p> Пол* : </p>
        <label for="genderM">  <input type="radio" id="genderM" name="gender" value="m" {{old('gender')=="m" ? 'checked' : ''}} {{empty(old('gender')) ? 'checked' : ''}}> Мужской </label><br/>
        <label for="genderF">  <input type="radio" id="genderF" name="gender" value="f" {{old('gender')=="f" ? 'checked' : ''}}> Женский </label>
      </div>
      <div class="form-group col-md-8 {{$errors->has('phone') ? 'has-error' : ''}}">
        <label for="phone">Номер телефона * </label>
        <span class="help-block">Введите номер сотового телефона в формате 8**********</span>
        <input class="form-control" type="tel" id="phone" name="phone" pattern="^(8)+\d{10}$" required maxlength="11" style="width:30%;" value="{{old('phone')}}" @if($errors->has('phone')) autofocus @endif>
        @if ($errors->has('phone'))
            <span class="help-block">
                <strong>{{ $errors->first('phone') }}</strong>
            </span>
        @endif
      </div>
      <div class="form-group col-md-8">
        <label for="address"> Адрес </label>
        <input class="form-control" type="text" id="address" name="address" value="{{old('address')}}">
      </div>

      <div class="col-md-8">
        <p class="lead"> Информация об автомобиле клиента </p>
      </div>
      <div class="form-group col-md-8 {{$errors->has('mark') ? 'has-error' : ''}}">
        <label for="mark" >Марка *</label>
        <input class="form-control" name="mark" id="mark" type="text" style="width:50%;" required value="{{old('mark')}}" @if($errors->has('mark')) autofocus @endif>
        @if($errors->has('mark'))
          <span class="help-block">
            <strong>{{$errors->first('mark')}}</strong>
          </span>
        @endif
      </div>
      <div class="form-group col-md-8 {{$errors->has('model') ? 'has-error' : ''}}">
        <label for="model" >Модель *</label>
        <input class="form-control" name="model" id="model" type="text" style="width:50%;" value="{{old('model')}}" required @if($errors->has('model')) autofocus @endif>
        @if($errors->has('model'))
          <span class="help-block">
            <strong>{{$errors->first('model')}}</strong>
          </span>
        @endif
      </div>
      <div class="form-group col-md-8 {{$errors->has('color') ? 'has-error' : ''}}">
        <label for="color" >Цвет кузова *</label>
        <input class="form-control" name="color" id="color" type="text" style="width:40%;"  value="{{old('color')}}" required @if($errors->has('color')) autofocus @endif>
        @if($errors->has('color'))
          <span class="help-block">
            <strong> {{$errors->first('color')}} </strong>
          </span>
        @endif
      </div>
      <div class="form-group col-md-8 {{$errors->has('number') ? 'has-error' : ''}}">
        <label for="number">Гос номер РФ * </label>
        <span class="help-block"></span>
        <input class="form-control" type="tel" id="number" name="number"  pattern="([(АВЕКМНОРСТУХ){1,3}0-9{5,6}]){6,8}" maxlength="9" style="width:30%;" value="{{old('number')}}" @if($errors->has('number')) autofocus @endif required>
        <span class="help-block"> Введите корректный номерной знак автомобиля вместе с кодом региона, без запятых (например, <span class="text-danger"><b>С227НА69</b></span>) </span>
        @if($errors->has('number'))
          <span class="help-block">
            <strong>{{$errors->first('number')}}</strong>
          </span>
        @endif
      </div>
      <div class="form-group col-md-5 col-md-offset-5">
        <button class="btn btn-success" type="submit">Добавить</button>
      </div>
    </form>
  </div>
</div>
@endsection

Parking/parking/resources/views/edit_client.blade.php
@extends('layouts.main_template')
@section('content')
<div class="container">
  <div class="row">
    <h1>Данные о клиенте</h1>
    @if (Session::has('msg'))
        <div class="alert alert-info">{{ Session::get('msg') }}</div>
    @endif


    <br>
    <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-body">
            <p class="lead"> Информация о клиенте </p>
              @foreach($client as $info)
              <form action="{{route('clients.update', $info->id)}}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group col-md-10 {{$errors->has('full_name') ? 'has-error' : ''}}">
                  <label for="full_name" >ФИО</label>
                  <input class="form-control" name="full_name" id="full_name" type="text" minlength="3" value="{{$info->full_name}}" @if($errors->has('full_name')) autofocus @endif >
                  @if($errors->has('full_name'))
                    <span class="help-block">
                      <strong> {{$errors->first('full_name')}} </strong>
                    </span>
                  @endif
                </div>
                <div class="form-group col-md-10">
                  <p> Пол* : </p>
                  <label for="genderM">  <input type="radio" id="genderM" name="gender" value="m" {{$info->gender=="m" ? 'checked' : ''}}> Мужской </label><br/>
                  <label for="genderF">  <input type="radio" id="genderF" name="gender" value="f" {{$info->gender=="f" ? 'checked' : ''}}> Женский </label>
                </div>
                <div class="form-group col-md-10 {{$errors->has('phone') ? 'has-error' : ''}}">
                  <label for="phone">Номер телефона * </label>
                  <span class="help-block">Введите номер сотового телефона в формате 8**********</span>
                  <input class="form-control" type="tel" id="phone" name="phone" pattern="^(8)+\d{10}$" required maxlength="11" style="width:30%;" value="{{$info->phone}}" @if($errors->has('phone')) autofocus @endif>
                  @if ($errors->has('phone'))
                      <span class="help-block">
                          <strong>{{ $errors->first('phone') }}</strong>
                      </span>
                  @endif
                </div>
                <div class="form-group col-md-10">
                  <label for="address"> Адрес </label>
                  <input class="form-control" type="text" id="address" name="address" value="{{$info->address}}">
                </div>
                <div class="form-group col-md-10 col-md-offset-5">
                  <button type="submit" class="btn btn-success">Сохранить</button>
                </div>
              </form>
              @endforeach

          </div>
        </div>
      </div>

      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-body">
            <p class="lead"> Автомобили клиента </p>
                @foreach($autos as $count => $auto)
                <form action="{{route('clients.update', $auto->id)}}" method="POST">
                  <input type="hidden" name="_method" value="PUT">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  <div class="panel panel-default">
                    <div class="panel-body">
                            <div class="form-group col-md-6 {{$errors->has('mark') ? 'has-error' : ''}}">
                              <label for="mark" >Марка *</label>
                              <input class="form-control" name="mark" id="mark" type="text" style="width:60%;" required value="{{$auto->mark}}" @if($errors->has('mark')) autofocus @endif>
                              @if($errors->has('mark'))
                                <span class="help-block">
                                  <strong>{{$errors->first('mark')}}</strong>
                                </span>
                              @endif
                            </div>

                            <div class="form-group col-md-6 {{$errors->has('model') ? 'has-error' : ''}}">
                              <label for="model" >Модель *</label>
                              <input class="form-control" name="model" id="model" type="text" style="width:60%;" value="{{$auto->model}}" required @if($errors->has('model')) autofocus @endif>
                              @if($errors->has('model'))
                                <span class="help-block">
                                  <strong>{{$errors->first('model')}}</strong>
                                </span>
                              @endif
                            </div>

                            <div class="form-group col-md-6 {{$errors->has('color') ? 'has-error' : ''}}">
                              <label for="color" >Цвет кузова *</label>
                              <input class="form-control" name="color" id="color" type="text" style="width:60%;"  value="{{$auto->color}}" required @if($errors->has('color')) autofocus @endif>
                              @if($errors->has('color'))
                                <span class="help-block">
                                  <strong> {{$errors->first('color')}} </strong>
                                </span>
                              @endif
                            </div>

                            <div class="form-group col-md-6 {{($errors->has('number') && (session('id_auto')==$auto->id)) ? 'has-error' : ''}}">
                              <label for="number">Гос номер РФ * </label>
                              <span class="help-block"></span>
                              <input class="form-control" type="tel" id="number" name="number"  pattern="([(АВЕКМНОРСТУХ){1,3}0-9{5,6}]){6,8}"  style="width:50%;" value="{{$auto->number}}" @if(($errors->has('number')) && (session('id_auto')==$auto->id)) autofocus value="{{old('number')}}" @endif required>
                              <span class="help-block"> Введите корректный номерной знак автомобиля вместе с кодом региона, без запятых (например, <span class="text-danger"><b>С227НА69</b></span>) </span>
                              @if(($errors->has('number')) && (session('id_auto')==$auto->id))
                                <span class="help-block">
                                  <strong>{{$errors->first('number')}}</strong>
                                </span>
                              @endif
                            </div>

                            <div class="form-group col-md-10 col-md-offset-5">
                              <button type="submit" class="btn btn-success">Сохранить</button>
                            </div>
                            </form>
                      </div>
                    </div>

                  @endforeach

              <div class="panel panel-default">
                <div class="panel-body">
                  <form action="{{route('client_store', ['id'=>$id])}}" method="POST">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  <div class="form-group col-md-6 {{$errors->has('mark_new') ? 'has-error' : ''}}">
                    <label for="mark_new" >Марка *</label>
                    <input class="form-control" name="mark_new" id="mark_new" type="text" style="width:60%;" required value="{{old('mark_new')}}">
                    @if($errors->has('mark_new'))
                      <span class="help-block">
                        <strong>{{$errors->first('mark_new')}}</strong>
                      </span>
                    @endif
                  </div>
                  <div class="form-group col-md-6 {{$errors->has('model_new') ? 'has-error' : ''}}">
                    <label for="model_new" >Модель *</label>
                    <input class="form-control" name="model_new" id="model_new" type="text" style="width:60%;" value="{{old('model_new')}}" required>
                    @if($errors->has('model_new'))
                      <span class="help-block">
                        <strong>{{$errors->first('model_new')}}</strong>
                      </span>
                    @endif
                  </div>
                  <div class="form-group col-md-6 {{$errors->has('color_new') ? 'has-error' : ''}}">
                    <label for="color_new" >Цвет кузова *</label>
                    <input class="form-control" name="color_new" id="color_new" type="text" style="width:60%;"  value="{{old('color_new')}}" required>
                    @if($errors->has('color_new'))
                      <span class="help-block">
                        <strong> {{$errors->first('color_new')}} </strong>
                      </span>
                    @endif
                  </div>


                  <div class="form-group col-md-6 {{$errors->has('number_new') ? 'has-error' : ''}}">
                    <label for="number_new">Гос номер РФ * </label>
                    <span class="help-block"></span>
                    <input class="form-control" type="text" id="number_new" name="number_new"  pattern="([(АВЕКМНОРСТУХ){1,3}0-9{5,6}]){6,8}"  style="width:50%;" value="{{old('number_new')}}" @if($errors->has('number_new')) autofocus @endif required>
                    <span class="help-block"> Введите корректный номерной знак автомобиля вместе с кодом региона, без запятых (например, <span class="text-danger"><b>С227НА69</b></span>) </span>
                    @if($errors->has('number_new'))
                      <span class="help-block">
                        <strong>{{$errors->first('number_new')}}</strong>
                      </span>
                    @endif
                  </div>
                  <div class="form-group col-md-5 col-md-offset-5">
                    <button class="btn btn-success" type="submit">Сохранить</button>
                  </div>
                </form>
                </div>
              </div>
              </div>
            </div>
          </div>
@endsection

Parking/parking/resources/views/main_page.blade.php
@extends('layouts.main_template')
@section('content')
<div id="menu" class="container">
  <div class="row">
      @if(Session::has('login'))
          <div class="alert alert-success"> {{Session::get('login')}} {{Auth::user()->login}}</div>
      @endif
      <div class="col-md-2 col-md-offset-2 block1" style="background-color:#d7d7d7;">
        <a href="{{route('clients.index')}}" class="menu-link">Все клиенты</a>
        <i class="fas fa-user-friends"></i>
      </div>

      <div class="col-md-2 block2" style="background-color:#d7d7d7;">
        <a href="{{route('show_auto')}}" class="menu-link">Статистика автостоянки</a>
        <i class="far fa-chart-bar"></i>
      </div>

      <div class="col-md-2 block3" style="background-color:#d7d7d7;">
        <a href="{{route('create_record')}}" class="menu-link">Новый клиент</a>
        <i class="fas fa-user-plus"></i>
      </div>
    </div>
</div>
@endsection

Parking/parking/resources/views/show_auto.blade.php
@extends('layouts.main_template')
@section('content')
<div class="container">
  <div class="row">
    <p class="lead"> Сейчас на автостоянке </p>
    @if(Session::has('msg'))
      <div class="alert alert-success">{{ Session::get('msg') }}</div>
    @endif
    <form class="form-inline" action="{{route('status_on')}}" method="post">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <div class="form-group">
        <select class="form-control" id="client" name="client" required {{count($clients)==0 ? 'disabled' : ''}}>
          <option hidden value=""> ФИО </option>
          @foreach($clients as $client)
            <option value="{{$client->id}}"> {{$client->full_name}} </option>
          @endforeach
        </select>
      </div>
      <div class="form-group col-md-offset-1">
        <select class="form-control" id="auto" name="auto" disabled required>
          <option hidden value=""> Автомобиль </option>
          <option> Fio1 </option>
        </select>
      </div>
      <button id="send" type="submit" class="btn btn-success col-md-offset-1" {{count($clients)==0 ? 'disabled' : ''}} >Въехал</button>
    </form>

    <hr>
    <br>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <tr class="success">
            <th style="width:30%;">ФИО</th>
            <th style="width:30%;">Автомобиль</th>
            <th style="width:15%;">Номер</th>
            <th style="width:10%; text-align:center;">Изменить статус</th>
          </tr>
          <tr>
            @if(count($autos)!=0)
              @foreach($autos as $number => $auto)
              <td>{{$auto->full_name}}</td>
              <td>{{$auto->mark}}: {{$auto->model}} ({{$auto->color}})</td>
              <td>{{$auto->number}}</td>
              <td style="width:10%; text-align:center;"> <a class="btn btn-warning" href="status_off/{{$auto->id}}"> Выехал </a></td>
            </tr>
            @endforeach
          @else
            <td colspan="4" style="text-align:center;" class="warning">В данный момент на автостоянке автомоблей нет</td>
          @endif
        </table>
        {{$autos->links()}}
    </div>
  </div>
</div>
@endsection


<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
$(document).ready(function() {
  $('#client').change( function () {
    var client=$(this).val();
    if(client=="0")
    {
      $('#auto').html('<option>Выберите из списка...</option>');
      $('#auto').attr('disabled', true);
      return(false);
    }
    $('#auto').attr('disabled', true);
    $('#auto').html('<option>Загрузка...</option>');
    var url = "{{route('get_auto')}}";
    $.ajaxSetup ({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });
    $.get(
        url,
        "client=" + client,
        function (result) {
            if (result.type == 'error') {
                $('#auto').html('<option> Список пуст </option>');
                $('#send').attr('disabled', true);
            }
            else {
                var options = '';
                $(result.auto_list).each(function() {
                    options += '<option value="' + $(this).attr('id') + '">' + $(this).attr('auto_list') + '</option>';
                });
                $('#auto').html(options);
                $('#auto').attr('disabled', false);
                $('#send').attr('disabled', false);
            }
        },
        "json"
    );
  })
});
</script>

Parking/parking/resources/views/show_clients.blade.php
@extends('layouts.main_template')
@section('content')
<div class="container">
  <div class="row">
    <p class="lead"> Клиенты автостоянки </p>
    @if(Session::has('msg'))
      <div class="alert alert-success">{{Session::get('msg')}}</div>
    @endif
    @if(Session::has('msg1'))
      <div class="alert alert-danger"> {{Session::get('msg1')}}</div>
    @endif
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <tr class="success">
            <th style="width:30%;">ФИО</th>
            <th style="width:30%;">Автомобиль</th>
            <th style="width:15%;">Номер</th>
            <th style="width:10%; text-align:center;">Редактировать</th>
            <th style="width:5%; text-align:center;">Удалить</th>
          </tr>
          <tr>
            @if(count($allRecord)!=0)
              @foreach($allRecord as $number => $record)
              <td>{{$record->full_name}}</td>
              <td>{{$record->mark}}: {{$record->model}} ({{$record->color}})</td>
              <td>{{$record->number}}</td>
              <td style="width:10%; text-align:center;"> <a href="clients/{{$record->id_client}}/edit" title="Редактировать данные клиента"> <button class="fas fa-pencil-alt"></button> </a> </td>
              <td style="width:10%; text-align:center;">
                <form id="delete-link" action="{{ route('delete_record', $record->id) }}" method="POST" >
                  <input type="hidden" name="_method" value="DELETE">
                  <button type="submit" class="fas fa-times" title="Удалить данные об автомобиле">  </button>
                    {{ csrf_field() }}
                </form>
              </td>
            </tr>
            @endforeach
          @else
            <td class="warning" colspan="5" style="text-align:center;"> Список клиентов пуст </td>
          @endif
        </table>
        {{$allRecord->links()}}
    </div>
  </div>
</div>
@endsection